name:                aoc2021
version:             0.1.0.0
github:              "githubuser/aoc2021"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

default-extensions: TupleSections

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2021#readme>

dependencies:
- base >= 4.7 && < 5
- split
- unordered-containers
- vector
- hashable

library:
  source-dirs: src

executables:
  day-01:
    main:                Main.hs
    source-dirs:         day-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
  day-02:
    main:                Main.hs
    source-dirs:         day-02
    dependencies:
    - aoc2021
  day-03:
    main:                Main.hs
    source-dirs:         day-03
    dependencies:
    - aoc2021
  day-04:
    main:                Main.hs
    source-dirs:         day-04
    dependencies:
    - aoc2021
  day-05:
    main:                Main.hs
    source-dirs:         day-05
    dependencies:
    - aoc2021
  day-06:
    main:                Main.hs
    source-dirs:         day-06
    dependencies:
    - aoc2021
  day-07:
    main:                Main.hs
    source-dirs:         day-07
    dependencies:
    - aoc2021
  day-08:
    main:                Main.hs
    source-dirs:         day-08
    dependencies:
    - aoc2021
  day-09:
    main:                Main.hs
    source-dirs:         day-09
    dependencies:
    - aoc2021
  day-10:
    main:                Main.hs
    source-dirs:         day-10
    dependencies:
    - aoc2021
  day-11:
    main:                Main.hs
    source-dirs:         day-11
    dependencies:
    - aoc2021
  day-12:
    main:                Main.hs
    source-dirs:         day-12
    dependencies:
    - aoc2021
  day-13:
    main:                Main.hs
    source-dirs:         day-13
    dependencies:
    - aoc2021
  day-14:
    main:                Main.hs
    source-dirs:         day-14
    dependencies:
    - aoc2021
  day-15:
    main:                Main.hs
    source-dirs:         day-15
    dependencies:
    - aoc2021
  day-16:
    main:                Main.hs
    source-dirs:         day-16
    dependencies:
    - aoc2021
tests:
  aoc2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
